version: "3"
services:
  app:
    build: .
    restart: always
    environment:
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - PORT=4170
    volumes:
      - docroot:/usr/src/app

  proxy:
    build: proxy
    restart: always
    ports:
      - "5670:5670"
    links:
      - app
    volumes:
      - docroot:/usr/src/app

volumes:
  docroot:
