version: "3"
services:
  app:
    build: .
    restart: always
    environment:
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - CLIENT_EMAIL=${CLIENT_EMAIL}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SECRET=${RECAPTCHA_SECRET}
      - PORT=4170
    volumes:
      - docroot:/usr/src/app

  proxy:
    build: proxy
    restart: always
    ports:
      - "5670:5670"
    links:
      - app
    volumes:
      - docroot:/usr/src/app

volumes:
  docroot:
